a=int(input("Enter first number : "))
b=int(input("Enter second number : "))
print("Bitwise AND is : ",a&b)
print("Bitwise OR is : ",a|b)
print("Bitwise XOR is : ",a^b)
print("Bitwise NOT of first num is : ",~a)
print("Bitwise NOT of second num is : ",~b)
print("Bitwise Left shift is : ",a<<b)
print("Bitwise Right shift is : ",a>>b)
